// questions.js — Banque de questions pour les 13 leçons

const LESSONS = [
  { id: 1,  title: "Nombres entiers naturels",          competence: "Activité Numérique" },
  { id: 2,  title: "Droites et points",                 competence: "Configurations du Plan" },
  { id: 3,  title: "Nombres décimaux relatifs",         competence: "Activité Numérique" },
  { id: 4,  title: "Segments",                          competence: "Configurations du Plan" },
  { id: 5,  title: "Cercles et disques",                competence: "Configurations du Plan" },
  { id: 6,  title: "Fractions",                         competence: "Activité Numérique" },
  { id: 7,  title: "Angles",                            competence: "Configurations du Plan" },
  { id: 8,  title: "Triangles",                         competence: "Configurations du Plan" },
  { id: 9,  title: "Proportionnalité",                  competence: "Organisation des Données" },
  { id: 10, title: "Figures symétriques par rapport à un point", competence: "Transformation du Plan" },
  { id: 11, title: "Parallélogramme",                   competence: "Configurations du Plan" },
  { id: 12, title: "Statistiques",                      competence: "Organisation des Données" },
  { id: 13, title: "Pavé droit et cylindre droit",      competence: "Configuration de l'Espace" }
];

const QUESTION_BANK = {
  1: [
    { q: "Lequel de ces nombres appartient à IN ?", opts: ["3,8", "2/3", "42", "0,02"], ans: 2, expl: "42 est un nombre entier naturel. 3,8 et 2/3 ne sont pas des entiers." },
    { q: "Comment note-t-on que 5 appartient à IN ?", opts: ["5 ∉ IN", "5 ∈ IN", "5 ⊂ IN", "5 > IN"], ans: 1, expl: "Le symbole ∈ signifie 'appartient à'. On écrit 5 ∈ IN." },
    { q: "17, 18 et 19 sont-ils des entiers naturels consécutifs ?", opts: ["Oui", "Non, il faut 17, 19 et 21", "Non, 18 n'est pas entier", "Impossible à dire"], ans: 0, expl: "17, 18 et 19 sont consécutifs car chacun suit directement le précédent (+1)." },
    { q: "Quel est le multiple de 9 qui suit 63 ?", opts: ["70", "72", "73", "81"], ans: 1, expl: "63 = 9×7, donc le suivant est 9×8 = 72." },
    { q: "Lequel est multiple de 3 ?", opts: ["124", "321", "235", "412"], ans: 1, expl: "3+2+1 = 6, multiple de 3. Donc 321 est divisible par 3." },
    { q: "Un nombre pair est un nombre entier naturel :", opts: ["divisible par 3", "divisible par 2", "qui se termine par 5", "divisible par 10"], ans: 1, expl: "Les nombres pairs sont les multiples de 2." },
    { q: "Quels sont les diviseurs de 12 parmi : 1, 4, 5, 7, 6 ?", opts: ["5 et 7", "1, 4 et 6", "4, 5 et 6", "1, 5 et 7"], ans: 1, expl: "1, 4 et 6 sont diviseurs de 12. 5 et 7 ne divisent pas 12." },
    { q: "1290 est-il divisible par 5 ?", opts: ["Non, car il se termine par 0", "Oui, car il se termine par 0", "Non, car il est pair", "Oui, car sa somme de chiffres est 12"], ans: 1, expl: "Un nombre est divisible par 5 s'il se termine par 0 ou 5." },
    { q: "La somme des chiffres de 783 est 18. Donc 783 est divisible par :", opts: ["2 seulement", "5 seulement", "3 et 9", "3 seulement"], ans: 2, expl: "18 est multiple de 9 et de 3. Donc 783 est divisible par 3 ET par 9." },
    { q: "Combien y a-t-il de diviseurs pour 56 ?", opts: ["4", "6", "8", "10"], ans: 2, expl: "Les diviseurs de 56 : 1, 2, 4, 7, 8, 14, 28, 56 — soit 8 diviseurs." },
    { q: "Le nombre 0 est-il un multiple de tout entier naturel ?", opts: ["Non, jamais", "Oui, car 0 = 0×n pour tout n", "Seulement de 1", "Seulement de 0"], ans: 1, expl: "0 = 0×n quel que soit n, donc 0 est multiple de tout entier naturel." },
    { q: "Parmi 209, 90, 119, lequel est multiple de 11 ?", opts: ["90", "119", "209", "Aucun"], ans: 2, expl: "209 = 11 × 19." },
    { q: "Un nombre est divisible par 9 quand :", opts: ["il se termine par 9", "la somme de ses chiffres est multiple de 9", "il est pair", "il se termine par 0"], ans: 1, expl: "Règle : divisible par 9 si la somme de ses chiffres est un multiple de 9." },
    { q: "Le plus petit diviseur d'un entier naturel non nul est :", opts: ["0", "1", "2", "L'entier lui-même"], ans: 1, expl: "Le plus petit diviseur est toujours 1, car n = 1×n." },
    { q: "6300 est divisible par 100 car :", opts: ["sa somme de chiffres vaut 9", "il se termine par 00", "il est pair", "il est multiple de 7"], ans: 1, expl: "Un nombre est divisible par 100 quand il se termine par 00." }
  ],
  2: [
    { q: "Comment note-t-on la droite passant par A et B ?", opts: ["[AB]", "(AB)", "{AB}", "AB"], ans: 1, expl: "Une droite passant par A et B se note (AB) avec des parenthèses." },
    { q: "Si C ∈ (D), cela signifie :", opts: ["C n'appartient pas à (D)", "C est parallèle à (D)", "C appartient à (D)", "C est perpendiculaire à (D)"], ans: 2, expl: "∈ signifie 'appartient à'." },
    { q: "Trois points sont alignés si :", opts: ["ils forment un triangle", "ils appartiennent à une même droite", "ils sont à égale distance", "deux d'entre eux se confondent"], ans: 1, expl: "Trois points sont alignés s'ils appartiennent tous à une même droite." },
    { q: "Par deux points distincts, on peut tracer combien de droites ?", opts: ["Aucune", "Une seule", "Deux", "Une infinité"], ans: 1, expl: "Par deux points distincts, il passe une droite et une seule." },
    { q: "La demi-droite d'origine A passant par B se note :", opts: ["(AB)", "[AB]", "[AB)", "[BA)"], ans: 2, expl: "Une demi-droite d'origine A passant par B se note [AB)." },
    { q: "Un point M d'une droite la partage en :", opts: ["trois parties", "deux demi-droites opposées", "un segment", "deux droites"], ans: 1, expl: "Un point M sur une droite détermine deux demi-droites opposées." },
    { q: "Deux droites sécantes ont :", opts: ["aucun point commun", "un seul point commun", "deux points communs", "infiniment de points communs"], ans: 1, expl: "Deux droites sécantes ont un seul point commun." },
    { q: "Deux droites perpendiculaires forment combien d'angles droits ?", opts: ["1", "2", "4", "3"], ans: 2, expl: "Deux droites perpendiculaires forment 4 angles droits de 90°." },
    { q: "Comment note-t-on que (L) est perpendiculaire à (H) ?", opts: ["(L) // (H)", "(L) ⊥ (H)", "(L) = (H)", "(L) × (H)"], ans: 1, expl: "⊥ signifie 'perpendiculaire à'." },
    { q: "Deux droites parallèles ont :", opts: ["un point commun", "aucun point commun", "deux points communs", "un angle droit"], ans: 1, expl: "Deux droites parallèles ne se coupent jamais." },
    { q: "Par un point P extérieur à (D), on peut tracer combien de droites parallèles à (D) ?", opts: ["Aucune", "Une seule", "Deux", "Une infinité"], ans: 1, expl: "Par un point extérieur, on ne trace qu'une seule parallèle à une droite donnée." },
    { q: "Deux droites sont parallèles si elles sont :", opts: ["sécantes", "perpendiculaires à une même droite", "sur la même feuille", "de longueurs égales"], ans: 1, expl: "Définition : deux droites parallèles sont perpendiculaires à une même droite." },
    { q: "Si A ∉ (D), cela signifie :", opts: ["A est sur (D)", "A n'est pas sur (D)", "A est le milieu de (D)", "A est l'origine de (D)"], ans: 1, expl: "∉ signifie 'n'appartient pas à'." },
    { q: "Une droite est :", opts: ["limitée à deux points", "illimitée d'un seul côté", "illimitée des deux côtés", "un segment très long"], ans: 2, expl: "Une droite est illimitée des deux côtés." },
    { q: "Par un point, combien peut-on tracer de droites perpendiculaires à (D) ?", opts: ["Aucune", "Une seule", "Deux", "Une infinité"], ans: 1, expl: "Par un point, on ne peut tracer qu'une seule perpendiculaire à une droite donnée." }
  ],
  3: [
    { q: "Comment note-t-on 3 billes en moins ?", opts: ["+3", "−3", "×3", "3"], ans: 1, expl: "Une quantité manquante se note avec le signe moins : −3." },
    { q: "L'ensemble des entiers relatifs est noté :", opts: ["IN", "ℤ", "ID", "IR"], ans: 1, expl: "L'ensemble des entiers relatifs est noté ℤ." },
    { q: "Parmi ces nombres, lequel est un entier relatif négatif ?", opts: ["+5", "0", "−7", "+12"], ans: 2, expl: "−7 est un entier relatif négatif." },
    { q: "Est-ce que 0 appartient à IN ?", opts: ["Oui", "Non", "Seulement comme négatif", "Cela dépend"], ans: 0, expl: "0 est le plus petit entier naturel. 0 ∈ IN." },
    { q: "La distance à zéro de (−5) est :", opts: ["−5", "5", "0", "+10"], ans: 1, expl: "La distance à zéro est le nombre sans son signe." },
    { q: "Les nombres (+3) et (−3) sont :", opts: ["égaux", "opposés", "perpendiculaires", "parallèles"], ans: 1, expl: "Même distance à zéro, signes contraires : ce sont des opposés." },
    { q: "Lequel est vrai : (−5) … (+2) ?", opts: ["(−5) > (+2)", "(−5) = (+2)", "(−5) < (+2)", "Impossible"], ans: 2, expl: "Tout positif est plus grand que tout négatif." },
    { q: "Comparer (−4) et (−9) :", opts: ["(−4) < (−9)", "(−4) > (−9)", "(−4) = (−9)", "Non comparable"], ans: 1, expl: "Pour deux négatifs : −4 a une plus petite distance à 0 que −9, donc −4 > −9." },
    { q: "Calcule (+5) + (+9) :", opts: ["−14", "+4", "+14", "−4"], ans: 2, expl: "Même signe + : 5+9=14, signe +. Résultat : +14." },
    { q: "Calcule (−10) + (−4) :", opts: ["+14", "−14", "+6", "−6"], ans: 1, expl: "Même signe − : 10+4=14, signe −. Résultat : −14." },
    { q: "Calcule (+12) + (−7) :", opts: ["+19", "−5", "+5", "−19"], ans: 2, expl: "Signes contraires : 12−7=5, signe du plus grand = +. Résultat : +5." },
    { q: "Sur une droite graduée, les négatifs sont placés :", opts: ["à droite de 0", "à gauche de 0", "au-dessus de 0", "en-dessous de 0"], ans: 1, expl: "Par convention, les négatifs sont à gauche de 0." },
    { q: "L'ensemble noté ID désigne :", opts: ["les entiers naturels", "les entiers relatifs", "les décimaux relatifs", "les fractions"], ans: 2, expl: "ID (ou 𝔻) = ensemble des nombres décimaux relatifs." },
    { q: "Calcule (−3,724) + (+1,235) :", opts: ["+4,959", "−2,489", "+2,489", "−4,959"], ans: 1, expl: "3,724−1,235=2,489. Signe dominant = −. Résultat : −2,489." },
    { q: "Les entiers relatifs positifs sont aussi des :", opts: ["décimaux négatifs", "entiers naturels", "fractions", "opposés"], ans: 1, expl: "+1, +2, +3… sont bien les entiers naturels 1, 2, 3…" }
  ],
  4: [
    { q: "Le segment [AB] se note aussi :", opts: ["(AB)", "[BA]", "AB)", "A-B"], ans: 1, expl: "[AB] et [BA] désignent le même segment." },
    { q: "La longueur du segment [AB] se note :", opts: ["[AB]", "(AB)", "AB", "AB²"], ans: 2, expl: "La longueur se note AB sans crochets." },
    { q: "Le milieu de [AB] est le point I tel que :", opts: ["AI > IB", "AI = IB", "AI < IB", "AI + IB = 0"], ans: 1, expl: "Le milieu partage le segment en deux parties égales : AI = IB." },
    { q: "La médiatrice de [AB] est :", opts: ["parallèle à [AB]", "perpendiculaire à [AB] passant par son milieu", "un segment de même longueur", "le milieu de [AB]"], ans: 1, expl: "La médiatrice est perpendiculaire à [AB] et passe par son milieu." },
    { q: "Pour comparer des longueurs de segments, on utilise :", opts: ["la règle seule", "le compas", "le rapporteur", "l'équerre"], ans: 1, expl: "Le compas permet de comparer et reporter des longueurs." },
    { q: "Si I est milieu de [AB] et AI = 3,5 cm, alors AB vaut :", opts: ["3,5 cm", "7 cm", "1,75 cm", "10,5 cm"], ans: 1, expl: "AB = AI + IB = 3,5 + 3,5 = 7 cm." },
    { q: "Le support d'un segment [AB] est :", opts: ["le milieu", "la droite (AB)", "la longueur AB", "la médiatrice"], ans: 1, expl: "Le support est la droite qui contient le segment." },
    { q: "Les extrémités du segment [PQ] sont :", opts: ["P uniquement", "Q uniquement", "P et Q", "le milieu"], ans: 2, expl: "Un segment a deux extrémités : P et Q." },
    { q: "Pour construire la médiatrice, on utilise :", opts: ["rapporteur seul", "règle seule", "règle et équerre", "compas seul"], ans: 2, expl: "On utilise la règle graduée (milieu) puis l'équerre (perpendiculaire)." },
    { q: "Un segment est une partie d'une droite :", opts: ["illimitée", "limitée par deux extrémités", "formée d'un seul point", "de longueur infinie"], ans: 1, expl: "Un segment est limité par ses deux extrémités." }
  ],
  5: [
    { q: "Le cercle de centre O et de rayon r se note :", opts: ["D(O;r)", "C(O;r)", "[O;r]", "O(r)"], ans: 1, expl: "Notation : C(O;r)." },
    { q: "Un rayon du cercle est :", opts: ["une corde passant par le centre", "un segment du centre à un point du cercle", "la distance entre deux points du cercle", "la moitié d'une corde"], ans: 1, expl: "Le rayon relie le centre à un point du cercle." },
    { q: "Un diamètre est une corde qui :", opts: ["est tangente au cercle", "passe par le centre", "est la plus courte corde", "mesure exactement 2 cm"], ans: 1, expl: "Le diamètre est une corde passant par le centre." },
    { q: "Si M ∈ C(O;r), alors OM = :", opts: ["r/2", "2r", "r", "r²"], ans: 2, expl: "Par définition, tout point du cercle est à distance r du centre." },
    { q: "Le disque D(O;r) se note :", opts: ["C(O;r)", "D(O;r)", "[O;r]", "δ(O;r)"], ans: 1, expl: "Notation du disque : D(O;r)." },
    { q: "Si M ∈ D(O;r), alors :", opts: ["OM > r", "OM = r uniquement", "OM ≤ r", "OM < 0"], ans: 2, expl: "M appartient au disque si OM ≤ r." },
    { q: "La formule du périmètre d'un cercle de rayon r est :", opts: ["P = π×r²", "P = 2×π×r", "P = π×r", "P = 4×r"], ans: 1, expl: "P = 2πr." },
    { q: "La valeur approchée de π utilisée en 6ème est :", opts: ["3,12", "3,14", "3,16", "3,41"], ans: 1, expl: "En 6ème, π ≈ 3,14." },
    { q: "L'aire d'un disque de rayon r est :", opts: ["A = 2πr", "A = πr", "A = π×r×r", "A = 4πr"], ans: 2, expl: "A = π × r²." },
    { q: "Un cercle de rayon 5 cm a un périmètre d'environ :", opts: ["15,7 cm", "31,4 cm", "78,5 cm", "10 cm"], ans: 1, expl: "P = 2 × 3,14 × 5 = 31,4 cm." },
    { q: "La différence entre cercle et disque :", opts: ["le cercle est plus grand", "le cercle est le contour, le disque inclut l'intérieur", "ce sont les mêmes", "le disque n'a pas de centre"], ans: 1, expl: "Cercle = contour ; disque = surface complète." }
  ],
  6: [
    { q: "Dans 3/5, le numérateur est :", opts: ["5", "3", "15", "2"], ans: 1, expl: "Le numérateur est le nombre du haut : 3." },
    { q: "Une fraction décimale a pour dénominateur :", opts: ["n'importe quel entier", "1, 10, 100, 1000…", "seulement 10", "un nombre impair"], ans: 1, expl: "Fraction décimale : dénominateur = puissance de 10." },
    { q: "0,7 en fraction décimale :", opts: ["7/100", "7/10", "70/1", "7/1000"], ans: 1, expl: "0,7 = 7/10." },
    { q: "Pour avoir une fraction égale, on multiplie numérateur et dénominateur par :", opts: ["des nombres différents", "un même nombre non nul", "0", "le dénominateur"], ans: 1, expl: "On multiplie (ou divise) par un même nombre non nul." },
    { q: "Simplifier une fraction, c'est :", opts: ["multiplier par un même nombre", "diviser num. et dén. par un même nombre", "additionner num. et dén.", "changer de dénominateur"], ans: 1, expl: "Simplifier = diviser num. et dén. par un même nombre." },
    { q: "Comparer 3/7 et 5/7 :", opts: ["3/7 est plus grande", "5/7 est plus grande", "Elles sont égales", "Impossible"], ans: 1, expl: "Même dénominateur, 5 > 3, donc 5/7 > 3/7." },
    { q: "8/9 comparée à 1 :", opts: ["8/9 > 1", "8/9 = 1", "8/9 < 1", "Impossible"], ans: 2, expl: "Numérateur (8) < dénominateur (9), donc 8/9 < 1." },
    { q: "Calculer 11/7 + 8/7 :", opts: ["19/14", "3/7", "19/7", "11/8"], ans: 2, expl: "Même dénominateur : (11+8)/7 = 19/7." },
    { q: "Pour additionner 4/5 et 3/2, on commence par :", opts: ["additionner les numérateurs", "réduire au même dénominateur", "multiplier", "simplifier"], ans: 1, expl: "Dénominateurs différents → réduire au même dénominateur (PPCM = 10)." },
    { q: "9/5 comparée à 1 :", opts: ["9/5 < 1", "9/5 = 1", "9/5 > 1", "Impossible"], ans: 2, expl: "Numérateur (9) > dénominateur (5), donc 9/5 > 1." },
    { q: "Calculer 5/3 + 9/4 :", opts: ["14/7", "47/12", "14/12", "20/12"], ans: 1, expl: "PPCM(3,4)=12 → 20/12 + 27/12 = 47/12." },
    { q: "Une fraction irréductible est :", opts: ["qu'on ne peut plus simplifier", "dont le numérateur vaut 1", "dont le dénominateur vaut 10", "qui vaut moins que 1"], ans: 0, expl: "Irréductible = plus de diviseur commun entre num. et dén. (sauf 1)." }
  ],
  7: [
    { q: "L'angle B̂AC a pour sommet :", opts: ["B", "A", "C", "Le milieu de BC"], ans: 1, expl: "La lettre du milieu dans B̂AC est le sommet : A." },
    { q: "Les côtés de l'angle B̂AC sont :", opts: ["les segments [AB] et [AC]", "les demi-droites [AB) et [AC)", "la droite (BC)", "les points B et C"], ans: 1, expl: "Les côtés d'un angle sont des demi-droites." },
    { q: "L'unité de mesure des angles est :", opts: ["le centimètre", "le degré (°)", "le radian", "le gramme"], ans: 1, expl: "En 6ème, on mesure en degrés (°)." },
    { q: "Un angle droit mesure :", opts: ["45°", "90°", "180°", "360°"], ans: 1, expl: "Angle droit = 90°." },
    { q: "Un angle aigu a une mesure :", opts: ["égale à 90°", "entre 90° et 180°", "entre 0° et 90°", "égale à 180°"], ans: 2, expl: "Angle aigu : 0° < mesure < 90°." },
    { q: "Un angle obtus a une mesure :", opts: ["entre 0° et 90°", "entre 90° et 180°", "égale à 90°", "égale à 0°"], ans: 1, expl: "Angle obtus : 90° < mesure < 180°." },
    { q: "Un angle plat mesure :", opts: ["90°", "180°", "270°", "360°"], ans: 1, expl: "Angle plat = 180°." },
    { q: "Un angle nul mesure :", opts: ["360°", "180°", "90°", "0°"], ans: 3, expl: "Angle nul = 0°." },
    { q: "La bissectrice d'un angle :", opts: ["est perpendiculaire", "passe par le sommet et partage en deux parties égales", "mesure la moitié de l'angle", "est parallèle aux côtés"], ans: 1, expl: "La bissectrice divise l'angle en deux angles égaux." },
    { q: "L'instrument pour mesurer un angle est :", opts: ["la règle", "le compas", "le rapporteur", "l'équerre"], ans: 2, expl: "Le rapporteur mesure et construit les angles." },
    { q: "La bissectrice d'un angle de 60° crée deux angles de :", opts: ["120°", "60°", "30°", "15°"], ans: 2, expl: "60° ÷ 2 = 30°." },
    { q: "L'équerre contient un angle de :", opts: ["45°", "60°", "90°", "180°"], ans: 2, expl: "L'équerre contient un angle droit de 90°." }
  ],
  8: [
    { q: "Les côtés du triangle ABC sont :", opts: ["les points A, B, C", "les segments [AB], [BC] et [CA]", "les droites (AB), (BC), (CA)", "les angles"], ans: 1, expl: "Les côtés sont les segments reliant les sommets." },
    { q: "Un triangle rectangle a :", opts: ["trois côtés égaux", "deux côtés perpendiculaires", "deux côtés égaux", "que des angles aigus"], ans: 1, expl: "Un triangle rectangle a un angle droit (deux côtés perpendiculaires)." },
    { q: "Un triangle isocèle a :", opts: ["trois côtés égaux", "deux côtés égaux", "un angle droit", "trois angles différents"], ans: 1, expl: "Isocèle = deux côtés de même longueur." },
    { q: "Un triangle équilatéral a :", opts: ["deux côtés égaux", "un angle droit", "trois côtés égaux", "trois angles différents"], ans: 2, expl: "Équilatéral = trois côtés égaux." },
    { q: "Une hauteur d'un triangle est :", opts: ["perpendiculaire au côté opposé passant par le sommet", "passant par un sommet et le milieu du côté opposé", "la médiatrice d'un côté", "la bissectrice d'un angle"], ans: 0, expl: "Hauteur : droite par un sommet, perpendiculaire au côté opposé." },
    { q: "Une médiane d'un triangle est :", opts: ["perpendiculaire au côté opposé", "passant par un sommet et le milieu du côté opposé", "perpendiculaire au milieu d'un côté", "la bissectrice d'un angle"], ans: 1, expl: "Médiane : droite par un sommet et le milieu du côté opposé." },
    { q: "La médiatrice d'un côté est :", opts: ["la hauteur", "la médiane", "perpendiculaire au côté passant par son milieu", "la bissectrice"], ans: 2, expl: "Médiatrice : perpendiculaire à un côté passant par son milieu." },
    { q: "La formule du périmètre du triangle ABC est :", opts: ["P = AB × BC", "P = AB + BC + CA", "P = (AB + BC) / 2", "P = AB²"], ans: 1, expl: "Périmètre = somme des trois côtés." },
    { q: "L'aire d'un triangle est :", opts: ["base + hauteur", "base × hauteur", "(base × hauteur) / 2", "base² / hauteur"], ans: 2, expl: "A = (b × h) / 2." },
    { q: "Le côté opposé au sommet A dans ABC est :", opts: ["[AB]", "[AC]", "[BC]", "Le plus long"], ans: 2, expl: "[BC] est le côté qui ne touche pas A." },
    { q: "Aire = (40 × 10) / 2 = ?", opts: ["400 m²", "200 m²", "20 m²", "800 m²"], ans: 1, expl: "(40 × 10) / 2 = 200 m²." },
    { q: "Le côté opposé à l'angle droit s'appelle :", opts: ["la hauteur", "l'hypoténuse", "la médiane", "la base"], ans: 1, expl: "L'hypoténuse est le côté opposé à l'angle droit." }
  ],
  9: [
    { q: "Deux grandeurs proportionnelles s'obtiennent en :", opts: ["ajoutant un même nombre", "multipliant par un même nombre non nul", "soustrayant un même nombre", "les divisant"], ans: 1, expl: "Proportionnalité : on multiplie par un coefficient constant." },
    { q: "Dans un tableau de proportionnalité, le rapport est :", opts: ["différent à chaque fois", "toujours le même", "toujours 0", "toujours 1"], ans: 1, expl: "Le rapport est constant : c'est le coefficient de proportionnalité." },
    { q: "Coefficient du tableau {6→72, 12→144} :", opts: ["6", "12", "18", "72"], ans: 1, expl: "72/6 = 12 et 144/12 = 12. Coefficient = 12." },
    { q: "L'échelle 1/10000 signifie que 1 cm représente :", opts: ["1 m", "10 m", "100 m", "1 km"], ans: 2, expl: "1 cm = 10000 cm = 100 m en réalité." },
    { q: "43% de 2000 F vaut :", opts: ["43 F", "430 F", "860 F", "4300 F"], ans: 2, expl: "2000 × 43/100 = 860 F." },
    { q: "Si on multiplie une colonne par 2, l'autre est :", opts: ["divisée par 2", "multipliée par 2", "inchangée", "multipliée par 4"], ans: 1, expl: "Propriété : multiplication par k dans les deux colonnes." },
    { q: "Pour vérifier la proportionnalité, on vérifie que :", opts: ["la somme des colonnes est égale", "le rapport col2/col1 est constant", "les valeurs augmentent", "les valeurs sont différentes"], ans: 1, expl: "Rapport constant = tableau de proportionnalité." },
    { q: "Bijou à 35000 F, bénéfice 12%. Prix de revente :", opts: ["39200 F", "4200 F", "30800 F", "35120 F"], ans: 0, expl: "Bénéfice = 35000×12/100 = 4200. Prix = 35000+4200 = 39200 F." },
    { q: "Effectifs, fréquences et % sont des grandeurs :", opts: ["non liées", "proportionnelles", "aléatoires", "entières"], ans: 1, expl: "Ces trois grandeurs forment un tableau de proportionnalité." },
    { q: "Le pourcentage est une proportion ramenée à :", opts: ["1", "10", "100", "1000"], ans: 2, expl: "Pourcentage = proportion sur 100." }
  ],
  10: [
    { q: "A et A' sont symétriques par rapport à I si :", opts: ["IA = IA'", "I est le milieu de [AA']", "IA' = 2IA", "A et A' sont alignés avec I"], ans: 1, expl: "Symétriques par rapport à I = I est le milieu de [AA']." },
    { q: "Le symétrique de I par rapport à lui-même est :", opts: ["Un point quelconque", "I lui-même", "Le point opposé", "Aucun"], ans: 1, expl: "I est son propre symétrique par rapport à I." },
    { q: "Le symétrique d'une droite par rapport à un point est :", opts: ["une droite perpendiculaire", "une droite parallèle", "le même point", "une demi-droite"], ans: 1, expl: "Le symétrique d'une droite est une droite parallèle." },
    { q: "Deux segments symétriques par rapport à un point ont :", opts: ["des longueurs différentes", "la même longueur", "la même origine", "la même direction seulement"], ans: 1, expl: "Segments symétriques = même longueur." },
    { q: "Deux angles symétriques par rapport à un point ont :", opts: ["des mesures différentes", "la même mesure", "la même position", "des mesures opposées"], ans: 1, expl: "Angles symétriques = même mesure." },
    { q: "Le symétrique du cercle C(O;r) par rapport à un point est :", opts: ["un cercle de rayon 2r", "un disque", "un cercle de même rayon r", "un segment"], ans: 2, expl: "Symétrique d'un cercle = cercle de même rayon." },
    { q: "Les symétriques de points alignés sont :", opts: ["non alignés", "aussi alignés", "en croix", "sur un cercle"], ans: 1, expl: "Les symétriques de points alignés sont aussi alignés." },
    { q: "Le centre de symétrie d'un segment est :", opts: ["son extrémité", "son milieu", "n'importe quel point", "la médiatrice"], ans: 1, expl: "Le milieu est le centre de symétrie du segment." },
    { q: "Le centre de symétrie d'un cercle est :", opts: ["un point du cercle", "le centre", "n'importe quel point", "un diamètre"], ans: 1, expl: "Le centre du cercle est son centre de symétrie." },
    { q: "Le centre de symétrie d'un parallélogramme est :", opts: ["un sommet", "l'intersection des diagonales", "le milieu d'un côté", "n'importe quel point"], ans: 1, expl: "L'intersection des diagonales est le centre de symétrie du parallélogramme." }
  ],
  11: [
    { q: "Un parallélogramme est un quadrilatère dont :", opts: ["tous les côtés sont égaux", "les diagonales sont égales", "les côtés opposés ont des supports parallèles", "tous les angles sont droits"], ans: 2, expl: "Définition : côtés opposés parallèles." },
    { q: "Les diagonales d'un parallélogramme se coupent :", opts: ["perpendiculairement", "en leur milieu", "aux sommets", "à angle droit"], ans: 1, expl: "Les diagonales se coupent en leur milieu." },
    { q: "Si les diagonales se coupent en leur milieu, le quadrilatère est :", opts: ["un trapèze", "un carré uniquement", "un parallélogramme", "un losange"], ans: 2, expl: "Réciproque : diagonales se coupant en leur milieu → parallélogramme." },
    { q: "Les côtés opposés d'un parallélogramme ont :", opts: ["des longueurs différentes", "la même longueur", "des supports perpendiculaires", "des longueurs proportionnelles"], ans: 1, expl: "Côtés opposés = même longueur." },
    { q: "Périmètre d'un parallélogramme de côtés a et b :", opts: ["P = a + b", "P = a × b", "P = 2(a + b)", "P = 4(a + b)"], ans: 2, expl: "P = 2×(a+b)." },
    { q: "Aire d'un parallélogramme (base b, hauteur h) :", opts: ["A = b + h", "A = (b×h)/2", "A = b×h", "A = 2×b×h"], ans: 2, expl: "A = base × hauteur." },
    { q: "Le centre d'un parallélogramme est :", opts: ["un sommet", "l'intersection des diagonales", "le milieu d'un côté", "un point quelconque"], ans: 1, expl: "Centre = intersection des diagonales." },
    { q: "Dans ABCD, [AB] et [DC] sont des côtés :", opts: ["consécutifs", "opposés", "perpendiculaires", "sécants"], ans: 1, expl: "[AB] et [DC] se font face : côtés opposés." },
    { q: "Périmètre d'un parallélogramme L=8, l=5 :", opts: ["16", "24", "26", "30"], ans: 2, expl: "P = 2×(8+5) = 26 cm." },
    { q: "Aire d'un parallélogramme base=8, hauteur=3 :", opts: ["24 cm²", "26 cm²", "40 cm²", "13 cm²"], ans: 0, expl: "A = 8×3 = 24 cm²." }
  ],
  12: [
    { q: "L'effectif d'une donnée est :", opts: ["le pourcentage", "le nombre de fois qu'elle apparaît", "la somme de toutes les données", "la fréquence en décimal"], ans: 1, expl: "Effectif = nombre d'apparitions de la donnée." },
    { q: "L'effectif total est :", opts: ["l'effectif le plus fréquent", "la somme de tous les effectifs", "la différence max-min", "la moyenne"], ans: 1, expl: "Effectif total = somme de tous les effectifs." },
    { q: "La fréquence d'une donnée est :", opts: ["effectif total / effectif", "effectif / effectif total", "effectif × 100", "effectif + total"], ans: 1, expl: "Fréquence = effectif ÷ effectif total." },
    { q: "La somme de toutes les fréquences (décimales) vaut :", opts: ["100", "0", "1", "L'effectif total"], ans: 2, expl: "Somme des fréquences = 1 toujours." },
    { q: "La somme des fréquences en pourcentage vaut :", opts: ["0%", "50%", "100%", "L'effectif total"], ans: 2, expl: "Somme des % = 100% toujours." },
    { q: "16 élèves sur 40 à Sirasso : la fréquence est :", opts: ["0,04", "0,4", "4", "16"], ans: 1, expl: "16/40 = 0,4." },
    { q: "Cette fréquence en pourcentage est :", opts: ["0,4%", "4%", "40%", "400%"], ans: 2, expl: "0,4 × 100 = 40%." },
    { q: "25% des voix sur 60 votants = :", opts: ["25 voix", "15 voix", "60 voix", "0,25 voix"], ans: 1, expl: "60 × 25/100 = 15 voix." },
    { q: "Effectifs, fréquences et % sont :", opts: ["non liés", "proportionnels", "aléatoires", "entiers"], ans: 1, expl: "Ces trois grandeurs sont proportionnelles entre elles." },
    { q: "Pour passer des % aux fréquences décimales, on :", opts: ["multiplie par 100", "divise par 100", "ajoute 100", "soustrait 100"], ans: 1, expl: "Fréquence = % ÷ 100. Ex: 40% → 0,4." }
  ],
  13: [
    { q: "Un pavé droit a :", opts: ["4 faces, 6 sommets", "6 faces, 8 sommets, 12 arêtes", "5 faces, 6 sommets", "6 faces, 10 sommets"], ans: 1, expl: "Pavé droit : 6 faces rectangulaires, 8 sommets, 12 arêtes." },
    { q: "Un cube est un pavé droit dont :", opts: ["les faces sont triangulaires", "toutes les arêtes ont la même longueur", "les diagonales se coupent", "les faces sont des disques"], ans: 1, expl: "Cube : toutes les arêtes ont la même longueur." },
    { q: "Le patron d'un solide est :", opts: ["sa vue de dessus", "son développement à plat", "son volume", "un cercle"], ans: 1, expl: "Le patron = développement à plat de toutes les faces." },
    { q: "Volume d'un pavé droit (L, l, h) :", opts: ["V = L + l + h", "V = 2(L+l+h)", "V = L × l × h", "V = (L×l×h)/2"], ans: 2, expl: "V = L × l × h." },
    { q: "Volume d'un cube d'arête a :", opts: ["V = 4a²", "V = 6a²", "V = a × a × a", "V = 3a"], ans: 2, expl: "V = a³." },
    { q: "Un cylindre droit est formé de :", opts: ["6 faces rectangulaires", "deux disques et une face latérale", "4 faces triangulaires", "un seul disque et un rectangle"], ans: 1, expl: "Cylindre = 2 disques (bases) + face latérale rectangulaire." },
    { q: "Le patron d'un cylindre contient :", opts: ["6 rectangles", "deux cercles et un rectangle", "deux triangles et un cercle", "seulement un rectangle"], ans: 1, expl: "Patron cylindre = 2 cercles + 1 rectangle." },
    { q: "Volume d'un cylindre (rayon r, hauteur h) :", opts: ["V = 2πrh", "V = πr²", "V = πr²h", "V = πrh²"], ans: 2, expl: "V = π × r² × h." },
    { q: "Aire latérale cylindre r=2, h=8, π=3,14 :", opts: ["50,24 cm²", "100,48 cm²", "200,96 cm²", "25,12 cm²"], ans: 1, expl: "Al = 2 × 3,14 × 2 × 8 = 100,48 cm²." },
    { q: "Aire totale pavé droit L=50, l=25, h=15 :", opts: ["4750 cm²", "18750 cm²", "9500 cm²", "2375 cm²"], ans: 0, expl: "AT = 2×(50×25) + 2×(50×15) + 2×(25×15) = 2500+1500+750 = 4750 cm²." }
  ]
};

module.exports = { LESSONS, QUESTION_BANK };
